version: "3.9"
services:
  yelloback:
    container_name: yello-backend
    image: yello-backend:local
    build: ./backend
    environment:
      YELLO_DB_CONN_STRING: "postgres://yellopguser:yellopwd@postgres:5432/yellodb"
      YELLO_SERVER_PORT: ":4004"
    ports:
      - "4004:4004"
    depends_on:
      - postgres
    networks:
      - yello-net
    
  postgres:
    container_name: yello_pgdb
    image: postgres:16.2
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "yellodb"
      POSTGRES_USER: "yellopguser"
      POSTGRES_PASSWORD: "yellopwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yellopguser -d yellodb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - yello-net

  
volumes:
  data:

networks:
  yello-net:
    driver: bridge
